import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'webapp-termsofuse',
  templateUrl: './termsofuse.component.html',
  styleUrls: ['./terms-of-use-page.scss']
})
export class TermsofuseComponent implements OnInit {
  tou_header = `Terms and Conditions of Use and Agreement`;
  tou_last_updated = `Last updated: Monday, January 10, 2022`;
  tou_ol = {
    list_item_1: `Acceptance of Terms and Conditions of Use.  Chasing Good, a New Jersey corporation (“Chasing Good,” “we,” “us” and/or “our”), provides and makes available the website at http://chasinggood.org (the “Site”) to you, the user (“User,” “you,” and/or “your”), subject to these Terms and Conditions of Use Agreement (the “Agreement”).  We reserve the right to update and change this Agreement, as well as our Privacy Policy, at any time without notice to you by posting updates and changes to the Site.  You are advised to check this Agreement from time to time for any updates or changes that may impact you, and if you do not accept such amendments, you must cease using the Site and any of the services rendered through the Site (collectively, the “Services”).  Your continued use of the Site and/or any of the Services after any amendment to this Agreement, as posted in accordance with the above, constitutes your agreement to, and acceptance of, the amended Agreement.  If you do not agree to any changes to this Agreement, do not continue to use any of the Services and do not access the Site.`,
    list_item_2: `Online Services.  The Site provides online resources including, but not limited to, online information regarding Chasing Good’s services, i.e., the Services.  Any new Services, resources or informational content added to the Site shall fall under the terms of this Agreement.  The Services and all online resources and informational content provide on the Site are expressly provided “as is” and “as available” basis without any warranty or condition, express, implied, or statutory, and are subject to the express Disclaimer of Warranty and Limitation of Liability provisions set forth below in this Agreement.  Chasing Good does not warrant that the Services will be uninterrupted, timely, secure, or error-free.  Chasing Good does not warrant that the results that may be obtained from the use of the Site and/or the Services will be accurate or reliable.  Chasing Good does not warrant that any of the Services will meet User’s expectations, or that any errors in the Services will be corrected.  Chasing Good assumes no responsibility for any data loss or other loss suffered by any User of the Site or the Services.  User is fully responsible for maintaining its computer equipment and Internet access to use the Site and engage with and utilize the Services.`,
    list_item_3: `Indemnity.  You agree to indemnify and hold Chasing Good, and, as applicable, its parent, subsidiaries, affiliates, officers, agents, co-branders or other partners, and employees, harmless from any claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of your violation of any term, condition or obligation of this Agreement, or your violation of any rights of another.`,
    list_item_4: {
      para1: `User Restrictions.  User shall not, and shall not permit any third party to, access or use the Site or any of the Services except as expressly permitted by the terms and conditions of this Agreement.  For purposes of clarity and without limiting the generality of the foregoing, User shall not, except as this Agreement expressly permits:`,
      list_item_a: `Copy, modify, create, or attempt to create derivative works or improvements of the Site or any of the Services;`,
      list_item_b: `Rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Site or any of the Services to any third party, including on or in connection with the internet or any time-sharing, service bureau, software as a service, cloud or other technology or service;`,
      list_item_c: `Translate, disassemble, reverse engineer, decompile, or decode the Site or any part thereof, or otherwise attempt to determine source code or protocols from the Site or any of the Services;`,
      list_item_d: `Attempt in any way to circumvent, bypass, or otherwise interfere with any security precautions or measures relating to the Site or any of the Services;`,
      list_item_e: `Input, upload, transmit or otherwise provide to or through the Site or any of the Services any information or materials that are unlawful or injurious, or contain, transmit or activate any software, hardware or other technology, device or means, including any virus, worm, malware or other malicious computer code, the purpose or effect of which is to (i) permit unauthorized access to, or to destroy, disrupt, disable, distort, or otherwise harm or impede in any manner any (A) computer, software, firmware, hardware, system or network or (B) any application or function of any of the foregoing or (C) the security, integrity, confidentiality or use of any data processed thereby, or (ii) prevent any authorized user from accessing or using the Site or any of the Services;`,
      list_item_f: `Damage, destroy, disrupt, disable, impair, interfere with, or otherwise impede or harm in any manner the Site or any of the Services, or Chasing Good’s provision of services to any third party, in whole or in part;`,
      list_item_g: `Remove, delete, alter, or obscure any trademarks, specifications, documentation, warranties or disclaimers, or any copyright, trademark, patent or other intellectual property or proprietary rights notices from the Site or any of the Services;`,
      list_item_h: `Access or use the Site or any of the Services in any manner or for any purpose that infringes, misappropriates or otherwise violates any intellectual property right (including registered and unregistered rights granted, applied for or otherwise now or hereafter in existence under or related to any patent, copyright, trademark, trade secret, database protection or other intellectual property rights laws, and all similar or equivalent rights or forms of protection, in any part of the world) or other right of any third party (including by any unauthorized access to, misappropriation, use, alteration, destruction or disclosure of the data of any other user or licensee of Chasing Good) or that violates any applicable law;`,
      list_item_i: `Access or use the Site or any of the Services for purposes of competitive analysis of the Site or any of the Services, the development, provision or use of a competing software service or product, or any other purpose that is to the detriment or commercial disadvantage of Chasing Good; or`,
      list_item_j: `Otherwise access or use the Site or any of the Services beyond the scope of the authorization granted hereunder.`,
      para2: `User acknowledges, understands, and agrees that violation of the provisions of this section may cause irreparable injuries to Chasing Good, and, in addition to the termination of this Agreement, Chasing Good shall be entitled to injunctive relief to prevent or discontinue any such violation, which shall be in addition to, and in no way in limitation of, any and all remedies or rights to recover damages that Chasing Good may have at law or in equity for the enforcement of such provision and/or for breach of this Agreement by User.  Further, User shall bear all costs, expenses, and damages, including, but not limited to, attorneys’ fees incurred by Chasing Good in connection with the enforcement of such provision.`
    },
    list_item_5: `Reservation of Rights and Ownership.  Chasing Good reserves all rights not expressly provided to User in this Agreement.  The Site and the Services are protected by copyright and other intellectual property laws and treaties.  Chasing Good is the owner and/or legal licensee of all title, interest, copyright, and other intellectual property rights in the Site and the Services.  This Agreement does not grant User any rights to trademarks or service marks of Chasing Good.  User further agrees that all of Chasing Good’s ideas, know-how, techniques, and any enhancements and modifications made to the Site and any of the Services provided therein in the future by or for Chasing Good are owned by Chasing Good and are subject to the terms and conditions of this Agreement.`,
    list_item_6: `Disclaimer of Warranties.  THE SITE, AND ANY AND ALL CONTENT AND INFORMATION PROVIDED THEREIN, AND ALL OF THE SERVICES MADE AVAILABLE BY AND THROUGH THE SITE, ARE EXPRESSLY PROVIDED “AS IS” AND “AS AVAILABLE” AND ALL WARRANTIES, EXPRESS OR IMPLIED, ARE EXPRESSLY DISCLAIMED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, MERCHANTABILITY OF ANY COMPUTER PROGRAM OR SOFTWARE, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY OF INFORMATIONAL CONTENT, OR SYSTEM INTEGRATION, OR TITLE AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT OF ANY THIRD PARTY’S INTELLECTUAL PROPERTY RIGHTS OR NON-INFRINGEMENT.`,
    list_item_7: `Limitation of Liability.  CHASING GOOD IS NOT LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, LOSS OF BUSINESS, LOSS OF PROFITS OR CONSEQUENTIAL DAMAGES, WHETHER BASED ON BREACH OF CONTRACT, BREACH OF WARRANTY, TORT, NEGLIGENCE, PRODUCT LIABILITY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.  SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES.  ACCORDINGLY, SOME OF THE LIMITATIONS OF THIS PARAGRAPH MAY NOT APPLY TO YOU.`,
    list_item_8: `Privacy Policy.  Chasing Good is firmly committed to protecting the privacy of your personal information.  By using the Site or any of the Services, user understands, acknowledges, and agrees that Chasing Good’s collection, usage, and disclosure of this personal information, if any, is governed by our Privacy Policy, the contents of which are incorporated by reference in its entirety into this Agreement.`,
    list_item_9: `No Partnership or Joint Venture. This Agreement shall not be construed to establish any form of partnership, agency, or joint venture of any kind between User and Chasing Good, nor to constitute either party as the agent, employee, legal representative, or any other form of representative of the other.`,
    list_item_10: `Severability. If any provision of this Agreement is held to be invalid, illegal, or unenforceable, the validity, legality, and enforceability of the remaining provisions will in no way be affected or impaired thereby so long as the intent of the parties can be preserved.`,
    list_item_11: `Law. This Agreement shall be deemed to have been made in the State of New Jersey, United States of America and all matters arising from or relating in any manner to the subject matter of this Agreement shall be interpreted, and the rights and liabilities of the parties determined, in accordance with the Laws of the State of New Jersey applicable to agreements executed, delivered, and performed within such State, without regard to the principles of conflicts of Laws thereof.  As part of the consideration for value received, each of the parties hereby consents to the exclusive jurisdiction of any state or federal court located within the State of New Jersey with respect to all matters arising from or relating in any manner to the subject matter of this Agreement, and further including, without limitation, any of the Services provided by Chasing Good to User under the terms of this Agreement.  With respect to all matters arising from or relating in any manner to the subject matter of this Agreement, each party hereby: (a) waives any objection to New Jersey as the venue of any action instituted hereunder, and (b) consents to the granting of such legal or equitable relief as is deemed appropriate by any aforementioned court.`,
    list_item_12: `Force Majeure. Neither party shall be liable for any failure or delay in the performance of its obligations under this Agreement if such failure or delay is due to acts of God, including, but not limited to, acts of the other party, fire, flood, natural catastrophe, acts of any government or of any civil or military authority, national emergencies, acts of terrorism, riots, war, insurrection, strikes, or any occurrence beyond the reasonable control of such party.`,
    list_item_13: `Entire Agreement. This Agreement comprises the complete and exclusive agreement between the parties regarding the subject matter hereof and supersedes any prior oral or written communications or understandings between the parties related to the subject matter hereof.`,
    list_item_14: `Successors. All the terms and provisions of this Agreement shall be binding upon and inure to the benefit of the parties and to their respective heirs, successors, permitted assigns and legal representatives. Chasing Good may assign this Agreement without notice to you and/or your consent.  User shall have no right to assign or otherwise transfer this Agreement, or any of the rights or obligations hereunder including, without limitation, any right or obligation arising from or in connection with the provision of Services by Chasing Good to User, to any third party without Chasing Good’s prior written consent, to be given or withheld in Chasing Good’s sole and absolute discretion.`,
    list_item_15: `Waiver.  The failure of Chasing Good to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision.  If any provision of this Agreement, including all terms and conditions and other documents it incorporates by reference, is held by a court of competent jurisdiction to be contrary to law, such provision shall be changed and interpreted so as to best accomplish the objectives of the original provision to the fullest extent allowed by law, and the remaining provision of this Agreement shall remain in full force and effect.  `,
    list_item_16: `Limitation on Claims.  Any claim arising under the terms of this Agreement must be brought within one (1) year after such claim or cause of action arose or be forever barred.`,
    list_item_17: `Violations.  Please report any known or suspected violations of this Agreement, including any suspected copyright or trademark violations, to chasinggoodnj@gmail.com.`,
  };
  
  constructor() { 
    console.log("Contrsuctor")
  }

  ngOnInit(): void {
    console.log("Initialized")
  }
}

