#stage 1
FROM node:latest as node
EXPOSE 8080
COPY . /var/www/web
WORKDIR /var/www/web
RUN npm install
RUN npm run build

#stage 2
FROM nginx:alpine
COPY --from=node /web/dist /usr/share/nginx/html
COPY --from=node /web/nginx-custom.conf /etc/nginx/conf.d/default.conf
